name: codecov upload
# only run on merge into main branch
on: 
  - push
  - pull_request

jobs:
  run-python:
    name: Python code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: checking pip 
        run:  python -m ensurepip --upgrade

      - name: Install
        run: |
          pip install -v coverage Cython cython-coverage numpy
          ENABLE_COVERAGE=True python setup.py develop

      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          coverage run -m unittest discover
          coverage xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3          
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          gcov: true