name: codecov upload
# only run on merge into main branch
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  run-python:
    name: Python code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: checking pip 
        run:  python -m ensurepip --upgrade

      - name: Install
        run: |
          pip install -v coverage Cython cython-coverage numpy pytest
          ENABLE_COVERAGE=True python setup.py develop

      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          coverage run -m pytest -vv -x
          coverage xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3          
        with:
          flags: pytest
